pipeline {
    agent any
    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/motorfireman/Test.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    docker.build('password_verification', 'password_verification/')
                }
            }
        }
        stage('Run Docker Container') {
            steps {
                script {
                    dockerImage = docker.image('password_verification')
                    dockerContainer = dockerImage.run('-p 5000:5000')
                }
            }
        }
        stage('Dependency Check') {
            steps {
                // Placeholder for dependency check commands
                echo 'Running dependency check...'
            }
        }
        stage('UI Testing') {
            steps {
                // Placeholder for UI testing commands
                echo 'Running UI tests...'
            }
        }
    }
    post {
        always {
            script {
                if (dockerContainer) {
                    dockerContainer.stop()
                }
            }
        }
    }
}
